[settings]
update_interval = 5
threshold = 0.0
samples_per_update = 1
ambient_percentages = [ 5.0, 95.5,]
screen_percentages = [ 0.0, 100.0,]
device_id = "0"
on_startup_enabled = false
preview_enabled = false

