[settings]
update_interval = 0.5
threshold = 0.0
samples_per_update = 10
ambient_percentages = [ 0.0, 100.0,]
screen_percentages = [ 0.0, 100.0,]
device_name = "HD Webcam"
preview_enabled = true
minimize_to_tray = true
