[settings]
update_interval = 10.0
threshold = 0.0
samples_per_update = 1
ambient_percentages = [ 0.0, 100.0,]
screen_percentages = [ 0.0, 100.0,]
device_name = "HD Webcam"
preview_enabled = false
minimize_to_tray = true
